### ISSUE TITLE
Color Gen Initial Concept

### ISSUE THREAD

**Issue by hanlunli** [trevorhuang1/cpt_warmup#4]
![image](https://github.com/trevorhuang1/cpt_warmup/assets/62855064/33d5e75c-8be5-4bd4-88d1-a76840a947e4)

**Comment by lakshusan** [comment]
# Color Generator

<a href="https://trevorhuang1.github.io/cpt_warmup//2023/12/03/js-colorgen-embed.html">Link to project (click)</a><br>
<a href="https://trevorhuang1.github.io/cpt_warmup//2023/11/14/binary-color-generator_IPYNB_2_.html">Link to code (click)</a>

- Input decimal values 0-255 in each box
- Code validates RGB values
- Converts RGB decimal to binary
- Displays converted RGB values in binary
- Displays final color

## Key Commits

- <a href="https://github.com/trevorhuang1/cpt_warmup/commit/8bf1214933ef5cbe29572b1d4caa4a233b67532a">input-based js color generator</a>
- <a href="https://github.com/trevorhuang1/cpt_warmup/commit/a9aa10d3a696960b662604dc98f4ea624c7f5fe5">sample color input</a>
